In [246]:
import numpy as np
import pandas as pd
from math import e, inf, sqrt
import random
from PIL import Image
import matplotlib.pyplot as plt

# activation 
def sig(x):
    y = 1/(1 + np.exp(-x))
    return y

# activation gradient
def sigDeriv(x):
    y = sig(x)*(1-sig(x))
    return y
x = np.array([1,2,3])
sigDeriv(x)



array([0.19661193, 0.10499359, 0.04517666])

In [247]:
#load raw data 
dat = pd.read_csv("Hello (Responses).csv")
numOfDatasets = len(dat)
dat = dat[["labels", "numbers"]]
dat

labels                                            numbers
0    human                  764630368926946241527490254892378
1    human                  738372947472930184615492017492036
2    human              0294727402847104726349284729405829028
3    human  3738847382829293838393947373929293838383939383...
4    human  9292737378291918273728282827383039737338389393938
..     ...                                                ...
367  human  4376816737940083464670466497649499734915729475...
368  human  8282751541452638839506070088654322568938585689...
369  human  3443135578081826252728262728292927272537383390...
370  human   162626373838393525833902762526273839372529394615
371  human              5184927535728399272715144920179473626

[372 rows x 2 columns]

In [248]:
# make a list of first 30 digits in each entry
datalist = list(dat["numbers"])
newList = []
for number in datalist:
    newList.append(number[:30])
newList

['764630368926946241527490254892',
 '738372947472930184615492017492',
 '029472740284710472634928472940',
 '373884738282929383839394737392',
 '929273737829191827372828282738',
 '918283929282726373637929193747',
 '958484736262627488493939487484',
 '958474737392038747493937376493',
 '827273840497474636382991826474',
 '262079472936202729739363964372',
 '811882282922929292922929229292',
 '385385385385273158961852843963',
 '040622043773104798307579842819',
 '464546678999973772929919177728',
 '991816161552517819200292761514',
 '627165263738484875838282716617',
 '627162646488364858588472626156',
 '383748283627468273737837472737',
 '281882737381819192727272718181',
 '362627272828282919192828289282',
 '499976184067735524377455993727',
 '316457946583721546897543824619',
 '637372827192928739192828291747',
 '383848495958265936493629473927',
 '838377327266284949605002917165',
 '749165926554294745295629573940',
 '102735153969141956191947152649',
 '193958573727594100191722747484',
 '203848472972650929

In [249]:
# make a new column for each digit in the entries (up to 30th digit) and add it as a column to dataframe 
for i in range(0, 30):
    # label each column for the position number of te digits it contains 
    dat[f"{i}"] = [num[i] for num in newList]
# drop the raw data column 
dat = dat.drop("numbers", axis=1)
dat
# dont covert to int now. can convert when in the numpy arrays (easier to convert the whole thing when we dont have a column that we want to keep as string)

labels  0  1  2  3  4  5  6  7  8  ... 20 21 22 23 24 25 26 27 28 29
0    human  7  6  4  6  3  0  3  6  8  ...  7  4  9  0  2  5  4  8  9  2
1    human  7  3  8  3  7  2  9  4  7  ...  5  4  9  2  0  1  7  4  9  2
2    human  0  2  9  4  7  2  7  4  0  ...  4  9  2  8  4  7  2  9  4  0
3    human  3  7  3  8  8  4  7  3  8  ...  9  3  9  4  7  3  7  3  9  2
4    human  9  2  9  2  7  3  7  3  7  ...  2  8  2  8  2  8  2  7  3  8
..     ... .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
367  human  4  3  7  6  8  1  6  7  3  ...  7  0  4  6  6  4  9  7  6  4
368  human  8  2  8  2  7  5  1  5  4  ...  0  6  0  7  0  0  8  8  6  5
369  human  3  4  4  3  1  3  5  5  7  ...  2  8  2  6  2  7  2  8  2  9
370  human  1  6  2  6  2  6  3  7  3  ...  3  9  0  2  7  6  2  5  2  6
371  human  5  1  8  4  9  2  7  5  3  ...  1  5  1  4  4  9  2  0  1  7

[372 rows x 31 columns]

In [250]:
# add rows of computer generated data equal to the number of human data collected
for i in range(0, numOfDatasets):
    tempList = []
    tempList.append("computer")
    for x in range(0, 30):
        tempList.append(str(random.randint(0, 9)))
    dat.loc[len(dat.index)] = tempList

dat

labels  0  1  2  3  4  5  6  7  8  ... 20 21 22 23 24 25 26 27 28 29
0       human  7  6  4  6  3  0  3  6  8  ...  7  4  9  0  2  5  4  8  9  2
1       human  7  3  8  3  7  2  9  4  7  ...  5  4  9  2  0  1  7  4  9  2
2       human  0  2  9  4  7  2  7  4  0  ...  4  9  2  8  4  7  2  9  4  0
3       human  3  7  3  8  8  4  7  3  8  ...  9  3  9  4  7  3  7  3  9  2
4       human  9  2  9  2  7  3  7  3  7  ...  2  8  2  8  2  8  2  7  3  8
..        ... .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
739  computer  1  5  1  2  0  4  0  6  7  ...  6  9  6  5  8  1  8  4  4  9
740  computer  9  2  6  7  6  3  8  2  2  ...  7  1  2  3  2  1  0  8  6  7
741  computer  9  4  2  7  2  9  0  4  4  ...  8  5  2  4  8  8  8  0  3  6
742  computer  0  6  3  8  1  1  1  5  6  ...  0  3  1  8  7  6  3  7  2  4
743  computer  2  3  8  1  5  2  1  2  1  ...  3  0  8  3  8  7  3  3  8  2

[744 rows x 31 columns]

In [251]:
numOfDatasets = len(dat.index) - 1
numOfDatasets

743

In [252]:
TrainingData = pd.DataFrame(dat.iloc[:, 1:]).to_numpy(copy=True, dtype=np.int32)
TrainingData

array([[7, 6, 4, ..., 8, 9, 2],
       [7, 3, 8, ..., 4, 9, 2],
       [0, 2, 9, ..., 9, 4, 0],
       ...,
       [9, 4, 2, ..., 0, 3, 6],
       [0, 6, 3, ..., 7, 2, 4],
       [2, 3, 8, ..., 3, 8, 2]])

In [253]:
TrainingData = pd.DataFrame(dat.iloc[:, 1:]).to_numpy(copy=True, dtype=np.int32)

# normalise data (make mean 0 and std 1)
mean = np.mean(TrainingData)
std = np.std(TrainingData)
TrainingData = (TrainingData - mean)/std
sum(TrainingData[0,:])

In [254]:
# used to test later 
def CheckOne(x):
    print("correct ans:", dat.iloc[x, 0])
CheckOne(random.randint(0,numOfDatasets))

correct ans: human


In [255]:
TrainingData[1, :].shape

(30,)

In [256]:
# separate training and test data by indexes 
testNum = 70
allIndex = list(range(0,numOfDatasets))
trainIndex = []
for i in range(0, numOfDatasets - testNum):
    x = random.randint(0, len(allIndex) - 1)
    trainIndex.append(allIndex[x])
    allIndex.pop(x)
testIndex = allIndex
print(len(testIndex))

70


In [257]:
x = np.array([[1,2,3],
              [1,2,3]])

y = np.array([[1,2,3]])

y.shape

(1, 3)

In [258]:
inputNumber = 30
Hidden1NeuronCount = 100
Hidden2NeuronCount = 100 
outputCount = 2  # first number is yes for human secnd number is yes for computer (maybe can use one number and check above/below 0.5)
learningRate = 0.1

# all weights from each row will lead to same neuron of the next layer 
# all weights from same column will act on same neuron of current layer
# first row weights are all weights that lead to first neuron in the next layer, etc
# first column weights are all weights that act on first neuron of current layer 
# weight.T = [all weights that act on first neuron of current layer]
#          [all weights that act on second neuron of current layer], etc...
# weight = [all weights that lead to first neuron of next layer]
#            [all weights that lead to second neuron of next layer], etc... 
# data will be a single column
# next layer calculated will be single column with all neurons (good)
# h,g,f,H,G,F == inactivated and activated hidden layers and final layers respectively

weights1 = np.random.uniform(-0.5,0.5,(Hidden1NeuronCount, inputNumber))
weights2 = np.random.uniform(-0.5,0.5,(Hidden2NeuronCount, Hidden1NeuronCount))
weights3 = np.random.uniform(-0.5,0.5,(outputCount, Hidden2NeuronCount))

biases1 = np.random.uniform(-0.1,0.1,(Hidden1NeuronCount, 1))
biases2 = np.random.uniform(-0.2,0.2,(Hidden2NeuronCount, 1))
biases3 = np.random.uniform(-0.3,0.3,(outputCount,1))

print(weights1.shape, weights2.shape, weights3.shape)
sig(weights1)

(100, 30) (100, 100) (2, 100)


array([[0.48284256, 0.38965813, 0.59556753, ..., 0.5234816 , 0.54492439,
        0.53446816],
       [0.50516389, 0.52758955, 0.45028317, ..., 0.46323904, 0.50238249,
        0.50618428],
       [0.38673298, 0.52767049, 0.41966918, ..., 0.54757443, 0.57519581,
        0.55141176],
       ...,
       [0.42928869, 0.52814761, 0.58361475, ..., 0.57572308, 0.415396  ,
        0.49802144],
       [0.38842327, 0.55975827, 0.52728374, ..., 0.39742318, 0.61944516,
        0.52993038],
       [0.44301516, 0.61691225, 0.39658873, ..., 0.40572847, 0.54076929,
        0.43953232]])

In [259]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

def test():
    # single test
    randomTest = testIndex[random.randint(0, testNum-1)] # only uses testdata for testing dont use data that will be iused in raining 
    prams = forwardProp(randomTest, weights1, weights2, weights3, biases1, biases2, biases3)
    modelAns, hidden1, hidden2, finallayer, UnactivatedHidden1, UnativatedHidden2, UnactivatedFinalLayer, data = prams
    ans = finallayer
    cost = np.sum((modelAns - finallayer)**2)
    CheckOne(randomTest)
    if ans.argmax() == 0:
        print("predicted: human")
    else:
        print("predicted: computer")

    return ans

def testMany(n):
    # test a bunch for accuracy calculations 
    correct = 0
    wrong = 0
    for i in range(0, n):
        randomTest = testIndex[random.randint(0, testNum-1)] # only uses testdata for testing dont use data that will be iused in raining
        finallayer = forwardProp(randomTest, weights1, weights2, weights3, biases1, biases2, biases3)[3]
        ans = softmax(finallayer)
        pred = ans.argmax()
        corr = dat.iloc[randomTest, 0]
        if corr == "human":
            corr = 0
        else:
            corr = 1

        if pred == corr:
            correct += 1
        else:
            wrong += 1
    print("accuracy:", str((correct/(correct + wrong))*100) + "%" , flush=False)



In [260]:
def forwardProp(x, weight1, weight2, weight3, bias1, bias2, bias3):
    # forward propagation 
    data = TrainingData[x,:].reshape(inputNumber,1)
    
    UnactivatedHidden1 = np.dot(weight1, data)
    hidden1 = sig(UnactivatedHidden1) + bias1

    UnativatedHidden2 = np.dot(weight2, hidden1)
    hidden2 = sig(UnativatedHidden2) + bias2

    UnactivatedFinalLayer = np.dot(weight3, hidden2)
    finalLayer = sig(UnactivatedFinalLayer) + bias3

    correctAns = dat.iloc[x,0]

    if correctAns == "human":
        correctAns = 0
    else:
        correctAns = 1

    modelAns = np.zeros((1,outputCount)) # create empty array
    modelAns[0,correctAns] = 1 # make the correct index become 1 rest remain 0
    return [modelAns, hidden1, hidden2, finalLayer, UnactivatedHidden1, UnativatedHidden2, UnactivatedFinalLayer, data]

forwardProp(700, weights1, weights2, weights3, biases1, biases2, biases3) #[3].shape

[array([[0., 1.]]),
 array([[ 1.09996511],
        [ 0.47580941],
        [ 0.93911334],
        [ 0.01315506],
        [ 0.91858557],
        [ 1.07177562],
        [-0.04245287],
        [ 0.08232992],
        [ 0.97840327],
        [ 0.04176716],
        [ 0.28321332],
        [ 0.89741825],
        [ 0.0594341 ],
        [ 0.12459976],
        [ 0.07443836],
        [-0.01589142],
        [ 0.13873995],
        [ 0.91910279],
        [ 1.05673697],
        [ 0.53426297],
        [ 0.72414236],
        [ 0.12835362],
        [ 0.95540454],
        [ 0.3793257 ],
        [-0.00674534],
        [-0.08397509],
        [ 0.89855193],
        [ 0.76809275],
        [ 0.72501713],
        [ 1.05074606],
        [ 0.24283853],
        [ 0.95635915],
        [ 0.11489052],
        [ 0.93198346],
        [ 1.00503422],
        [ 0.02547279],
        [ 1.04085974],
        [ 1.05915651],
        [ 0.06500008],
        [-0.03469861],
        [ 0.08725567],
        [ 0.36642584],
        [ 1.05

In [261]:
biases3



array([[ 0.17566834],
       [-0.03498841]])

In [262]:
x = np.array(([1,2,3],
             [1,2,3]))
np.sum(x, 0)

array([2, 4, 6])

In [263]:
# optimise weights 
def backProp(params):
# h,g,f,H,G,F == inactivated and activated hidden layers and final layers respectively
    global weights1, weights2, weights3, biases1, biases2, biases3
    modelAns, H, G, F, h, g, f, data = params
    modelAns = modelAns.reshape(outputCount,1)
    cost = np.mean((modelAns - F)**2)
    print("cost:", cost)
    
    dCdF = -2*(modelAns - F)
    dCdf = dCdF * sigDeriv(f)

    dCdG = np.sum(dCdf * weights3, 0).reshape(Hidden2NeuronCount,1)

    dCostdWeights3 = np.ones_like(weights3) * G.reshape(1, Hidden2NeuronCount) * dCdf
    
    dGdg = sigDeriv(g)

    dCdH = np.sum((dGdg * dCdG) * weights2, 0).reshape(Hidden1NeuronCount,1)

    dCostdWeights2 = np.ones_like(weights2) * H.reshape(1, Hidden1NeuronCount) * dCdG * dGdg

    dHdh = sigDeriv(h)

    dCostdWeights1 = np.ones_like(weights1) * data.reshape(1, inputNumber) * dCdH * dHdh

    dCostdBiases3 = dCdF # this is prb not the gradient wrt to the bias but rather proportionate number to the amt u want the bias to change
    dCostdBiases2 = dCdG 
    dCostdBiases1 = dCdH
    weights3 -= dCostdWeights3 * learningRate
    weights2 -= dCostdWeights2 * learningRate
    weights1 -= dCostdWeights1 * learningRate
    biases3 -= dCostdBiases3 * learningRate
    biases2 -= dCostdBiases2 * learningRate
    biases1 -= dCostdBiases1 * learningRate
    return #cost

backProp(forwardProp(3, weights1, weights2, weights3, biases1, biases2, biases3))

cost: 0.26584810468840486


In [264]:
# train of some data 
for i in range(numOfDatasets - testNum):
    print(i)
    x = trainIndex[i] # dont train on testdata
    backProp(forwardProp(i, weights1, weights2, weights3, biases1, biases2, biases3))


0
cost: 0.1375698144252605
1
cost: 0.027105442346472223
2
cost: 0.0007889378933023536
3
cost: 0.0016762416153806717
4
cost: 0.0048205818731934386
5
cost: 0.0002876166043312426
6
cost: 0.0004631246497486483
7
cost: 0.004059272545139551
8
cost: 0.0026003549985431384
9
cost: 0.004863652373007992
10
cost: 0.011914507449649047
11
cost: 0.009976311872405205
12
cost: 0.020966205750390963
13
cost: 0.03335275975313268
14
cost: 0.006480299417639425
15
cost: 0.00455633705868716
16
cost: 0.0010511214493628383
17
cost: 0.00014114432869113093
18
cost: 0.0002872160568972231
19
cost: 0.011700908710537021
20
cost: 0.014642346457105857
21
cost: 0.0020577039840743183
22
cost: 0.0061096005680524625
23
cost: 0.003004256857912214
24
cost: 0.006273309614464491
25
cost: 0.02426473516991303
26
cost: 0.023946786399522267
27
cost: 0.004109795250716579
28
cost: 0.03024145960674016
29
cost: 0.0012975045978618465
30
cost: 0.0011923136492927953
31
cost: 0.012420314706323697
32
cost: 0.005164204161462175
33
cost: 0.0

cost: 0.0029373592302362962
414
cost: 0.004457943010498516
415
cost: 0.010050929193127623
416
cost: 0.00341043672330002
417
cost: 0.001131924959223665
418
cost: 0.0024528558243922653
419
cost: 0.009247949973662144
420
cost: 0.0030930944234920754
421
cost: 0.0010465255049523186
422
cost: 0.0044268723078861975
423
cost: 0.01620629415035968
424
cost: 0.010079390965068094
425
cost: 0.0036592809781609836
426
cost: 0.0006924692313546111
427
cost: 0.003607581882736022
428
cost: 0.0013521364439313787
429
cost: 0.0027115516489063566
430
cost: 0.00033556297107956525
431
cost: 0.003914708732211014
432
cost: 0.0045701346757378546
433
cost: 9.928298983058044e-05
434
cost: 0.008694251341669464
435
cost: 0.024121953957376117
436
cost: 0.005833546610400985
437
cost: 0.0014959765600420674
438
cost: 0.01684510670982145
439
cost: 0.0003571924750579086
440
cost: 0.0028906276638532356
441
cost: 0.0025655955700889205
442
cost: 0.00032726782349738027
443
cost: 0.0015969721748170652
444
cost: 0.00484348355902

In [316]:
test() # do one to visualise 
# observed that model always predicts computer


correct ans: computer
predicted: computer


array([[0.00410674],
       [0.98940406]])

In [356]:
testMany(50) # do many for accuracy calculation 
# testing random 50 from 70 with repeats (not good)
# does not work prb not enough data 

accuracy: 52.0%
