In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

# activation 
def sig(x):
    y = 1/(1 + np.exp(-x))
    return y

# activation gradient
def sigDeriv(x):
    y = sig(x)*(1-sig(x))
    return y
x = np.array([1,2,3])
sigDeriv(x)



array([0.19661193, 0.10499359, 0.04517666])

In [2]:
#load raw data 
dat = pd.read_csv("Hello (Responses).csv")
numOfDatasets = len(dat)
dat = dat[["labels", "numbers"]]
dat

labels                                            numbers
0    human                  764630368926946241527490254892378
1    human                  738372947472930184615492017492036
2    human              0294727402847104726349284729405829028
3    human  3738847382829293838393947373929293838383939383...
4    human  9292737378291918273728282827383039737338389393938
..     ...                                                ...
367  human  4376816737940083464670466497649499734915729475...
368  human  8282751541452638839506070088654322568938585689...
369  human  3443135578081826252728262728292927272537383390...
370  human   162626373838393525833902762526273839372529394615
371  human              5184927535728399272715144920179473626

[372 rows x 2 columns]

In [3]:
# make a list of first 30 digits in each entry
datalist = list(dat["numbers"])
newList = []
for number in datalist:
    newList.append(number[:30])
newList

['764630368926946241527490254892',
 '738372947472930184615492017492',
 '029472740284710472634928472940',
 '373884738282929383839394737392',
 '929273737829191827372828282738',
 '918283929282726373637929193747',
 '958484736262627488493939487484',
 '958474737392038747493937376493',
 '827273840497474636382991826474',
 '262079472936202729739363964372',
 '811882282922929292922929229292',
 '385385385385273158961852843963',
 '040622043773104798307579842819',
 '464546678999973772929919177728',
 '991816161552517819200292761514',
 '627165263738484875838282716617',
 '627162646488364858588472626156',
 '383748283627468273737837472737',
 '281882737381819192727272718181',
 '362627272828282919192828289282',
 '499976184067735524377455993727',
 '316457946583721546897543824619',
 '637372827192928739192828291747',
 '383848495958265936493629473927',
 '838377327266284949605002917165',
 '749165926554294745295629573940',
 '102735153969141956191947152649',
 '193958573727594100191722747484',
 '203848472972650929

In [4]:
# make a new column for each digit in the entries (up to 30th digit) and add it as a column to dataframe 
for i in range(0, 30):
    # label each column for the position number of te digits it contains 
    dat[f"{i}"] = [num[i] for num in newList]
# drop the raw data column 
dat = dat.drop("numbers", axis=1)
dat
# dont covert to int now. can convert when in the numpy arrays (easier to convert the whole thing when we dont have a column that we want to keep as string)

labels  0  1  2  3  4  5  6  7  8  ... 20 21 22 23 24 25 26 27 28 29
0    human  7  6  4  6  3  0  3  6  8  ...  7  4  9  0  2  5  4  8  9  2
1    human  7  3  8  3  7  2  9  4  7  ...  5  4  9  2  0  1  7  4  9  2
2    human  0  2  9  4  7  2  7  4  0  ...  4  9  2  8  4  7  2  9  4  0
3    human  3  7  3  8  8  4  7  3  8  ...  9  3  9  4  7  3  7  3  9  2
4    human  9  2  9  2  7  3  7  3  7  ...  2  8  2  8  2  8  2  7  3  8
..     ... .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
367  human  4  3  7  6  8  1  6  7  3  ...  7  0  4  6  6  4  9  7  6  4
368  human  8  2  8  2  7  5  1  5  4  ...  0  6  0  7  0  0  8  8  6  5
369  human  3  4  4  3  1  3  5  5  7  ...  2  8  2  6  2  7  2  8  2  9
370  human  1  6  2  6  2  6  3  7  3  ...  3  9  0  2  7  6  2  5  2  6
371  human  5  1  8  4  9  2  7  5  3  ...  1  5  1  4  4  9  2  0  1  7

[372 rows x 31 columns]

In [5]:
# add rows of computer generated data equal to the number of human data collected
for i in range(0, numOfDatasets):
    tempList = []
    tempList.append("computer")
    for x in range(0, 30):
        tempList.append(str(random.randint(0, 9)))
    dat.loc[len(dat.index)] = tempList

dat

labels  0  1  2  3  4  5  6  7  8  ... 20 21 22 23 24 25 26 27 28 29
0       human  7  6  4  6  3  0  3  6  8  ...  7  4  9  0  2  5  4  8  9  2
1       human  7  3  8  3  7  2  9  4  7  ...  5  4  9  2  0  1  7  4  9  2
2       human  0  2  9  4  7  2  7  4  0  ...  4  9  2  8  4  7  2  9  4  0
3       human  3  7  3  8  8  4  7  3  8  ...  9  3  9  4  7  3  7  3  9  2
4       human  9  2  9  2  7  3  7  3  7  ...  2  8  2  8  2  8  2  7  3  8
..        ... .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
739  computer  7  3  1  3  4  9  6  5  9  ...  6  9  2  4  2  4  9  6  0  4
740  computer  6  9  3  0  3  4  0  2  8  ...  9  2  8  4  9  3  2  2  5  6
741  computer  3  6  2  7  6  2  7  8  7  ...  2  1  2  9  3  1  5  0  7  0
742  computer  3  6  1  9  5  5  7  8  2  ...  3  3  4  3  5  8  9  0  7  9
743  computer  2  3  7  6  4  0  0  0  2  ...  8  9  1  6  0  5  5  9  1  0

[744 rows x 31 columns]

In [6]:
numOfDatasets = len(dat.index) - 1
numOfDatasets

743

In [7]:
TrainingData = pd.DataFrame(dat.iloc[:, 1:]).to_numpy(copy=True, dtype=np.int32)
TrainingData

array([[7, 6, 4, ..., 8, 9, 2],
       [7, 3, 8, ..., 4, 9, 2],
       [0, 2, 9, ..., 9, 4, 0],
       ...,
       [3, 6, 2, ..., 0, 7, 0],
       [3, 6, 1, ..., 0, 7, 9],
       [2, 3, 7, ..., 9, 1, 0]])

In [8]:
TrainingData = pd.DataFrame(dat.iloc[:, 1:]).to_numpy(copy=True, dtype=np.int32)

# normalise data (make mean 0 and std 1)
mean = np.mean(TrainingData)
std = np.std(TrainingData)
TrainingData = (TrainingData - mean)/std
sum(TrainingData[0,:])

0.49180083045877043

In [9]:
# used to test later 
def CheckOne(x):
    print("correct ans:", dat.iloc[x, 0])
CheckOne(random.randint(0,numOfDatasets))

correct ans: computer


In [10]:
TrainingData[1, :].shape

(30,)

In [11]:
# separate training and test data by indexes 
testNum = 70
allIndex = list(range(0,numOfDatasets))
trainIndex = []
for i in range(0, numOfDatasets - testNum):
    x = random.randint(0, len(allIndex) - 1)
    trainIndex.append(allIndex[x])
    allIndex.pop(x)
testIndex = allIndex
print(len(testIndex))

70


In [12]:
x = np.array([[1,2,3],
              [1,2,3]])

y = np.array([[1,2,3]])

y.shape

(1, 3)

In [13]:
inputNumber = 30
Hidden1NeuronCount = 100
Hidden2NeuronCount = 100 
outputCount = 2  # first number is yes for human secnd number is yes for computer (maybe can use one number and check above/below 0.5)
learningRate = 0.1

# all weights from each row will lead to same neuron of the next layer 
# all weights from same column will act on same neuron of current layer
# first row weights are all weights that lead to first neuron in the next layer, etc
# first column weights are all weights that act on first neuron of current layer 
# weight.T = [all weights that act on first neuron of current layer]
#          [all weights that act on second neuron of current layer], etc...
# weight = [all weights that lead to first neuron of next layer]
#            [all weights that lead to second neuron of next layer], etc... 
# data will be a single column
# next layer calculated will be single column with all neurons (good)
# h,g,f,H,G,F == inactivated and activated hidden layers and final layers respectively

weights1 = np.random.uniform(-0.5,0.5,(Hidden1NeuronCount, inputNumber))
weights2 = np.random.uniform(-0.5,0.5,(Hidden2NeuronCount, Hidden1NeuronCount))
weights3 = np.random.uniform(-0.5,0.5,(outputCount, Hidden2NeuronCount))

biases1 = np.random.uniform(-0.1,0.1,(Hidden1NeuronCount, 1))
biases2 = np.random.uniform(-0.2,0.2,(Hidden2NeuronCount, 1))
biases3 = np.random.uniform(-0.3,0.3,(outputCount,1))

print(weights1.shape, weights2.shape, weights3.shape)
sig(weights1)

(100, 30) (100, 100) (2, 100)


array([[0.44537831, 0.61438853, 0.54971579, ..., 0.60237112, 0.52776774,
        0.4045107 ],
       [0.49033579, 0.50005536, 0.51983871, ..., 0.41609216, 0.58606208,
        0.42920229],
       [0.56857351, 0.49013797, 0.45232415, ..., 0.48966434, 0.50054184,
        0.50733094],
       ...,
       [0.53763841, 0.57205759, 0.50675082, ..., 0.61119192, 0.4303711 ,
        0.40818583],
       [0.41345259, 0.47802076, 0.4204836 , ..., 0.5653659 , 0.53626293,
        0.42465539],
       [0.60606926, 0.50264593, 0.51224445, ..., 0.58715867, 0.57903642,
        0.50803348]])

In [14]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

def test():
    # single test
    randomTest = testIndex[random.randint(0, testNum-1)] # only uses testdata for testing dont use data that will be iused in raining 
    prams = forwardProp(randomTest, weights1, weights2, weights3, biases1, biases2, biases3)
    modelAns, hidden1, hidden2, finallayer, UnactivatedHidden1, UnativatedHidden2, UnactivatedFinalLayer, data = prams
    ans = finallayer
    cost = np.sum((modelAns - finallayer)**2)
    CheckOne(randomTest)
    if ans.argmax() == 0:
        print("predicted: human")
    else:
        print("predicted: computer")

    return ans

def testMany(n):
    # test a bunch for accuracy calculations 
    correct = 0
    wrong = 0
    for i in range(0, n):
        randomTest = testIndex[random.randint(0, testNum-1)] # only uses testdata for testing dont use data that will be iused in raining
        finallayer = forwardProp(randomTest, weights1, weights2, weights3, biases1, biases2, biases3)[3]
        ans = softmax(finallayer)
        pred = ans.argmax()
        corr = dat.iloc[randomTest, 0]
        if corr == "human":
            corr = 0
        else:
            corr = 1

        if pred == corr:
            correct += 1
        else:
            wrong += 1
    print("accuracy:", str((correct/(correct + wrong))*100) + "%" , flush=False)



In [15]:
def forwardProp(x, weight1, weight2, weight3, bias1, bias2, bias3):
    # forward propagation 
    data = TrainingData[x,:].reshape(inputNumber,1)
    
    UnactivatedHidden1 = np.dot(weight1, data)
    hidden1 = sig(UnactivatedHidden1) + bias1

    UnativatedHidden2 = np.dot(weight2, hidden1)
    hidden2 = sig(UnativatedHidden2) + bias2

    UnactivatedFinalLayer = np.dot(weight3, hidden2)
    finalLayer = sig(UnactivatedFinalLayer) + bias3

    correctAns = dat.iloc[x,0]

    if correctAns == "human":
        correctAns = 0
    else:
        correctAns = 1

    modelAns = np.zeros((1,outputCount)) # create empty array
    modelAns[0,correctAns] = 1 # make the correct index become 1 rest remain 0
    return [modelAns, hidden1, hidden2, finalLayer, UnactivatedHidden1, UnativatedHidden2, UnactivatedFinalLayer, data]

forwardProp(700, weights1, weights2, weights3, biases1, biases2, biases3) #[3].shape

[array([[0., 1.]]),
 array([[ 0.27430146],
        [ 0.42544371],
        [ 0.18805746],
        [ 0.48064805],
        [ 0.81792723],
        [ 1.0090756 ],
        [ 0.26401925],
        [ 0.19420489],
        [ 0.12332969],
        [ 0.57374682],
        [ 0.10564819],
        [ 0.44037196],
        [ 0.13483845],
        [ 0.89421859],
        [ 0.3393531 ],
        [ 0.60867084],
        [ 0.79462873],
        [ 0.11977975],
        [-0.00865708],
        [ 0.65756942],
        [ 0.73138229],
        [ 0.43170352],
        [ 0.62791149],
        [ 0.51714277],
        [ 0.04915902],
        [ 0.08600046],
        [ 0.48764791],
        [ 1.00699056],
        [ 0.80639619],
        [ 0.10362215],
        [ 0.08121615],
        [ 0.2763277 ],
        [ 0.15935776],
        [ 0.62094509],
        [ 0.43988842],
        [ 0.22228887],
        [ 0.18063494],
        [-0.04545305],
        [ 0.99415401],
        [ 0.6100827 ],
        [ 0.41273888],
        [ 0.1537577 ],
        [ 0.92

In [16]:
biases3



array([[-0.0531504 ],
       [ 0.27849951]])

In [17]:
x = np.array(([1,2,3],
             [1,2,3]))
np.sum(x, 0)

array([2, 4, 6])

In [18]:
# optimise weights 
def backProp(params):
# h,g,f,H,G,F == inactivated and activated hidden layers and final layers respectively
    global weights1, weights2, weights3, biases1, biases2, biases3
    modelAns, H, G, F, h, g, f, data = params
    modelAns = modelAns.reshape(outputCount,1)
    cost = np.mean((modelAns - F)**2)
    print("cost:", cost)
    
    dCdF = -2*(modelAns - F)
    dCdf = dCdF * sigDeriv(f)

    dCdG = np.sum(dCdf * weights3, 0).reshape(Hidden2NeuronCount,1)

    dCostdWeights3 = np.ones_like(weights3) * G.reshape(1, Hidden2NeuronCount) * dCdf
    
    dGdg = sigDeriv(g)

    dCdH = np.sum((dGdg * dCdG) * weights2, 0).reshape(Hidden1NeuronCount,1)

    dCostdWeights2 = np.ones_like(weights2) * H.reshape(1, Hidden1NeuronCount) * dCdG * dGdg

    dHdh = sigDeriv(h)

    dCostdWeights1 = np.ones_like(weights1) * data.reshape(1, inputNumber) * dCdH * dHdh

    dCostdBiases3 = dCdF # this is prb not the gradient wrt to the bias but rather proportionate number to the amt u want the bias to change
    dCostdBiases2 = dCdG 
    dCostdBiases1 = dCdH
    weights3 -= dCostdWeights3 * learningRate
    weights2 -= dCostdWeights2 * learningRate
    weights1 -= dCostdWeights1 * learningRate
    biases3 -= dCostdBiases3 * learningRate
    biases2 -= dCostdBiases2 * learningRate
    biases1 -= dCostdBiases1 * learningRate
    return #cost

backProp(forwardProp(3, weights1, weights2, weights3, biases1, biases2, biases3))

cost: 0.3895477032387077


In [19]:
# train of some data 
for i in range(numOfDatasets - testNum):
    print(i)
    x = trainIndex[i] # dont train on testdata
    backProp(forwardProp(i, weights1, weights2, weights3, biases1, biases2, biases3))


0
cost: 0.041473585994783645
1
cost: 0.01761845214598007
2
cost: 0.016046613888640968
3
cost: 0.003582588843729431
4
cost: 0.009192013758999348
5
cost: 0.0026758591511102563
6
cost: 0.0006257753734050363
7
cost: 0.0037208310748675357
8
cost: 0.0011706018676687253
9
cost: 0.001061356481628011
10
cost: 0.002530277748961667
11
cost: 0.002172461073197801
12
cost: 0.0011897075171782617
13
cost: 0.0003275738694489957
14
cost: 0.001960847474988954
15
cost: 5.088111218741082e-06
16
cost: 0.004988425787205431
17
cost: 0.0011461473801332833
18
cost: 0.0018573723728469416
19
cost: 0.0019769317739727816
20
cost: 0.0019421263609525848
21
cost: 0.0010821891205880954
22
cost: 0.00040751543799566285
23
cost: 0.0003488089794023477
24
cost: 0.00022335814429251484
25
cost: 0.0001843352434870365
26
cost: 0.0009649820642577431
27
cost: 3.286416622246021e-05
28
cost: 0.0012280541609817994
29
cost: 0.001385524688831812
30
cost: 0.00022730018520423302
31
cost: 0.0011784233901198805
32
cost: 0.0042874412930224

In [20]:
test() # do one to visualise 
# observed that model always predicts computer


correct ans: computer
predicted: computer


array([[-0.07137669],
       [ 0.99611634]])

In [31]:
testMany(300) # do many for accuracy calculation 
# testing random 50 from 70 with repeats (not good)
# 50-60% accuracy 

accuracy: 56.00000000000001%
